# Generated by Django 3.2.7 on 2022-05-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='accident',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
