# Generated by Django 3.2.7 on 2022-05-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aas', '0003_notifications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='type_of_notification',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='user_revoker',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='user_sender',
        ),
        migrations.AddField(
            model_name='notifications',
            name='near_by_hos',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='notifications',
            name='vehicle',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
    ]
